# This is a basic workflow to help you get started with Actions
name: CI
# Controls when the action will run. 
on:
  schedule:
    - cron: "0 4 * * 1"
  push:
    branches: [ main ] 
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout galaxy-tools-compchem
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}
        repository: planemo-autoupdate/galaxytools
        ref: master
        path: galaxytools

    - name: Checkout galaxy-tools-compchem
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}
        repository: planemo-autoupdate/galaxy-tools-compchem
        ref: master
        path: galaxy-tools-compchem
        
    - uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    # Download github cli
    - name: Download github cli
      run: |
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
        sudo apt-add-repository https://cli.github.com/packages
        sudo apt update
        sudo apt install gh
        
    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo "Setting up virtual env..."
        pip3 install wheel
        sudo pip3 install virtualenv
        virtualenv .au
        source .au/bin/activate
        #pip install conda
        
        echo "Installing planemo..."
        pip install https://github.com/simonbray/planemo/archive/autoupdate-sb.zip  # install from Simon's fork for now
        #planemo --help
        planemo conda_init

        # git credentials
        git config --global user.email "sbray@informatik.uni-freiburg.de"
        git config --global user.name "planemo-autoupdate"
        echo ${{ secrets.PAT }} > token.txt
        gh auth login --with-token < token.txt
        
        cd galaxy-tools-compchem
        echo "Adding upstream..."
        git remote add upstream https://github.com/galaxycomputationalchemistry/galaxy-tools-compchem.git

        echo "Getting git remote..."
        git remote -v

        echo "Pulling latest from upstream..."

        # new_branch_name="version_autoupdate_"$(date '+%Y-%m-%d')
        
        #if [ `git branch --list $new_branch_name` ]
        #then
        #    git push origin --delete $new_branch_name
        #fi

        git pull --all
        
        REPOS=$(planemo ci_find_repos)
        echo $REPOS
        for REPO in $REPOS; do
          echo $REPO
          # checkout branch, create if it doesn't exist
          git checkout -b $REPO upstream/master || git checkout -b $REPO upstream/master

          echo "Running autoupdate command..."
          planemo autoupdate $REPO

          if [[ $(git diff) ]]
          then
            git status

            echo "Adding..."
            git add .

            echo "Committing..."
            git commit -m "Version Autoupdate"            

            echo "Push branch to remote..."
            git push origin $REPO
            echo "Creating a PR..."
            # gh pr create --base master --head $GITHUB_ACTOR:$REPO --title "$REPO autoupdate" --body "Autoupdate conda package versions" --repo galaxycomputationalchemistry/galaxy-tools-compchem

          fi

        done
