# This is a basic workflow to help you get started with Actions
name: CI
# Controls when the action will run. 
on:
  schedule:
    - cron: "0 4 * * 1"
  push:
    branches: [ main ] 
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout galaxy-tools-compchem
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}
        repository: planemo-autoupdate/galaxytools
        ref: master
        path: galaxytools

    - name: Checkout galaxy-tools-compchem
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}
        repository: planemo-autoupdate/galaxy-tools-compchem
        ref: master
        path: galaxy-tools-compchem
        
    - uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    # Download github cli
    - name: Download github cli
      run: |
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
        sudo apt-add-repository https://cli.github.com/packages
        sudo apt update
        sudo apt install gh
        
    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo "Setting up virtual env..."
        pip3 install wheel
        sudo pip3 install virtualenv
        virtualenv .au
        source .au/bin/activate
        #pip install conda
        
        echo "Installing planemo..."
        pip install https://github.com/simonbray/planemo/archive/autoupdate-sb.zip  # install from Simon's fork for now
        #planemo --help
        planemo conda_init

        cd galaxytools

        echo "Authenticating..."
        echo ${{ secrets.PAT }} > token.txt
        gh auth login --with-token < token.txt

        echo "List PR..."
        gh issue list -A $GITHUB_ACTOR -s open --repo bgruening/galaxytools